# Generated by Django 4.0.6 on 2022-08-06 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter_info',
            fields=[
                ('chapter_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('chapter_no', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=50)),
                ('chapter_intro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='code_submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.CharField(max_length=1000)),
                ('success_code', models.BooleanField(default=False)),
                ('score', models.CharField(max_length=10)),
                ('tries', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.chapter_info')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_submit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
