# Generated by Django 4.0.6 on 2022-08-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_code_submit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_submit',
            name='chapter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submit_chapID', to='users.chapter_info'),
        ),
    ]
