# Generated by Django 4.0.6 on 2022-08-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_code_submit_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_submit',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='code_submit',
            name='tries',
            field=models.IntegerField(),
        ),
    ]
