# Generated by Django 4.0.6 on 2022-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_code_submit_score_alter_code_submit_tries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_submit',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='code_submit',
            name='tries',
            field=models.IntegerField(default=1),
        ),
    ]
